### ISSUE TITLE
Contact listing - details view not showing for remote contacts.

### ISSUE THREAD

**Issue by abhijit-ecsion** [abhijit-ecsion/SmartEmail#13]
Contact listing - details view not showing for remote contacts.

 Issue -
    - Details View not working as we are taking all the custom fields from DB with the specified table no but as we have taken all contact listing from Remote tables so it gives error for showing details view.
    - Earlier we have added application contact tables join for showing and listing contacts but it should be external contacts table.

Solution - 
Need to change Join from SalesTrakingContacts Table columns to ExternalContacts Table columns in
 Dynamic Query.

![Contact Detail View Error](https://user-images.githubusercontent.com/49864205/112436570-dafd9100-8d6b-11eb-9358-447217ad008c.png)

**Comment by abhijit-ecsion** [comment]
**API Error getFieldDefinitionsByTableId**

CALL stp_getPageDetailByTableId_v2("12", "12", "35bf8c13-b479-42a8-bee0-8ddb14d0bb83","e36c0c70-80ac-11ea-a9c5-0a0d3a4dd1a4","1","20","145","37bc19da-c4d9-4b02-b87e-c0905eea9c24" , "241ad4e7-d55a-4bc2-b163-6da273766e1e")
E:\applications\ecsion\smartemailapi\node_modules\mysql\lib\protocol\Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

TypeError: Cannot read property 'length' of undefined
    at Query.<anonymous> (E:\applications\ecsion\smartemailapi\modules\detailsviewModules.js:138:27)
    at Query.<anonymous> (E:\applications\ecsion\smartemailapi\node_modules\mysql\lib\Connection.js:526:10)
    at Query._callback (E:\applications\ecsion\smartemailapi\node_modules\mysql\lib\Connection.js:488:16)
    at Query.Sequence.end (E:\applications\ecsion\smartemailapi\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query.ErrorPacket (E:\applications\ecsion\smartemailapi\node_modules\mysql\lib\protocol\sequences\Query.js:92:8)
    at Protocol._parsePacket (E:\applications\ecsion\smartemailapi\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (E:\applications\ecsion\smartemailapi\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (E:\applications\ecsion\smartemailapi\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (E:\applications\ecsion\smartemailapi\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (E:\applications\ecsion\smartemailapi\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (E:\applications\ecsion\smartemailapi\node_modules\mysql\lib\Connection.js:526:10)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:250:12)
    at readableAddChunk (_stream_readable.js:237:11)
    at Socket.Readable.push (_stream_readable.js:195:10)
    at TCP.onread (net.js:586:20)

------------------------------------------------------------------------------------------------------------------------------------
SP Error stp_getPageDetailByTableId_v2

Error Code: 1267 Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='
